import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, ArrowRight, CheckCircle2, CircleAlert, Globe2, Mail, Moon, RefreshCw, Router, Settings, Sun, X } from 'lucide-react'
import './index.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api'
const t = {
  en: { title:'AI Email Router', subtitle:'Digital receptionist control center', logs:'Routing logs', all:'All status', forwarded:'Forwarded', failed:'Failed', sender:'Sender', subject:'Subject', department:'AI department', status:'Status', date:'Date', action:'Action', route:'Route manually', noLogs:'No routing logs yet', refresh:'Refresh', process:'Check inbox now', settings:'Settings', save:'Save settings', cancel:'Cancel', language:'العربية', light:'Light mode', dark:'Dark mode', saved:'Settings saved', manual:'Manual routing', choose:'Choose department', send:'Forward email', close:'Close', interval:'Polling interval (seconds)', target:'Department email addresses', connection:'Connections' },
  ar: { title:'موجّه البريد بالذكاء الاصطناعي', subtitle:'مركز تحكم موظف الاستقبال الرقمي', logs:'سجل التوجيه', all:'كل الحالات', forwarded:'تم التوجيه', failed:'فشل', sender:'المرسل', subject:'الموضوع', department:'القسم المكتشف', status:'الحالة', date:'التاريخ', action:'الإجراء', route:'توجيه يدوي', noLogs:'لا توجد سجلات توجيه بعد', refresh:'تحديث', process:'فحص البريد الآن', settings:'الإعدادات', save:'حفظ الإعدادات', cancel:'إلغاء', language:'English', light:'الوضع الفاتح', dark:'الوضع الداكن', saved:'تم حفظ الإعدادات', manual:'توجيه يدوي', choose:'اختر القسم', send:'توجيه البريد', close:'إغلاق', interval:'مدة الفحص (بالثواني)', target:'عناوين البريد للأقسام', connection:'الاتصالات' }
}

function App() {
  const [lang, setLang] = useState(localStorage.lang || 'en')
  const [dark, setDark] = useState(localStorage.dark === 'true')
  const [logs, setLogs] = useState([])
  const [departments, setDepartments] = useState([])
  const [filter, setFilter] = useState('all')
  const [busy, setBusy] = useState(false)
  const [modal, setModal] = useState(false)
  const [routeLog, setRouteLog] = useState(null)
  const [settings, setSettings] = useState(null)
  const [notice, setNotice] = useState('')
  const tr = t[lang] || t['en']
  const dir = lang === 'ar' ? 'rtl' : 'ltr'

  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.dark = dark }, [dark])
  useEffect(() => { document.documentElement.dir = dir; localStorage.lang = lang }, [lang, dir])
  const load = async () => { setBusy(true); try { const [l, d] = await Promise.all([fetch(`${API}/logs`), fetch(`${API}/departments`)]); setLogs(await l.json()); setDepartments(await d.json()) } finally { setBusy(false) } }
  useEffect(() => { load() }, [])
  const process = async () => { setBusy(true); await fetch(`${API}/process`, { method:'POST' }); await load() }
  const openSettings = async () => { const r = await fetch(`${API}/settings`); setSettings(await r.json()); setModal(true) }
  const saveSettings = async (e) => { e.preventDefault(); await fetch(`${API}/settings`, { method:'PUT', headers:{'Content-Type':'application/json'}, body:JSON.stringify(settings) }); setModal(false); setNotice(tr.saved); setTimeout(()=>setNotice(''), 2500) }
  const filtered = logs.filter(x => filter === 'all' || x.status.toLowerCase() === filter)
  const setField = (key, value) => setSettings(s => ({ ...s, [key]:value }))

  return <div className="app-shell min-h-screen bg-slate-50 text-slate-900 transition-colors dark:bg-slate-950 dark:text-slate-100" dir={dir}>
    <header className="topbar sticky top-0 z-10 border-b border-slate-200 dark:border-slate-800">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4">
        <div className="flex items-center gap-3"><div className="brand-mark rounded-xl bg-gradient-to-br from-indigo-500 to-violet-700 p-2.5 text-white"><Router size={23}/></div><div><h1 className="text-lg font-bold tracking-tight">{tr.title}</h1><p className="text-xs text-slate-500 dark:text-slate-400">{tr.subtitle}</p></div></div>
        <div className="flex items-center gap-2"><button title={dark ? tr.light : tr.dark} onClick={()=>setDark(!dark)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button onClick={()=>setLang(lang==='en'?'ar':'en')} className="flex items-center gap-1.5 rounded-lg px-2.5 py-2 text-sm text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800"><Globe2 size={17}/>{tr.language}</button><button onClick={openSettings} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"><Settings size={18}/></button></div>
      </div>
    </header>
    <main className="mx-auto max-w-7xl px-5 py-8">
      <div className="mb-7 grid gap-4 sm:grid-cols-3"><Stat icon={<Mail/>} label={tr.logs} value={logs.length} color="indigo"/><Stat icon={<CheckCircle2/>} label={tr.forwarded} value={logs.filter(x=>x.status==='Forwarded').length} color="emerald"/><Stat icon={<CircleAlert/>} label={tr.failed} value={logs.filter(x=>x.status==='Failed').length} color="rose"/></div>
      <section className="data-panel overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-5 py-4 dark:border-slate-800"><div><h2 className="font-semibold">{tr.logs}</h2><p className="mt-0.5 text-xs text-slate-500">{logs.length} {lang==='ar'?'رسالة':'messages'}</p></div><div className="flex items-center gap-2"><select value={filter} onChange={e=>setFilter(e.target.value)} className="control rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none dark:border-slate-700 dark:bg-slate-800"><option value="all">{tr.all}</option><option value="forwarded">{tr.forwarded}</option><option value="failed">{tr.failed}</option></select><button onClick={load} className="rounded-lg border border-slate-200 p-2 text-slate-600 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800"><RefreshCw size={17} className={busy?'animate-spin':''}/></button><button onClick={process} className="primary-button flex items-center gap-2 rounded-lg bg-indigo-600 px-3 py-2 text-sm font-medium text-white hover:bg-indigo-700"><Activity size={16}/>{tr.process}</button></div></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm rtl:text-right"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-950/40 dark:text-slate-400"><tr><th className="px-5 py-3">{tr.date}</th><th className="px-5 py-3">{tr.sender}</th><th className="px-5 py-3">{tr.subject}</th><th className="px-5 py-3">{tr.department}</th><th className="px-5 py-3">{tr.status}</th><th className="px-5 py-3">{tr.action}</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{filtered.map(log=><tr key={log.id} className="table-row"><td className="whitespace-nowrap px-5 py-4 text-xs text-slate-500">{new Date(log.date).toLocaleString(lang==='ar'?'ar-SA':'en-US')}</td><td className="max-w-[190px] truncate px-5 py-4" title={log.sender}>{log.sender}</td><td className="max-w-[230px] truncate px-5 py-4 font-medium" title={log.subject}>{log.subject}</td><td className="px-5 py-4"><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-medium text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">{log.department || '—'}</span></td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1.5 text-xs font-medium ${log.status==='Forwarded'?'text-emerald-600':'text-rose-600'}`}>{log.status==='Forwarded'?<CheckCircle2 size={15}/>:<CircleAlert size={15}/>} {log.status==='Forwarded'?tr.forwarded:tr.failed}</span></td><td className="px-5 py-4">{log.status==='Failed'&&<button onClick={()=>setRouteLog(log)} className="flex items-center gap-1 text-xs font-medium text-indigo-600 hover:text-indigo-800">{tr.route}<ArrowRight size={14}/></button>}</td></tr>)}{filtered.length===0&&<tr><td colSpan="6" className="px-5 py-16 text-center text-sm text-slate-500">{tr.noLogs}</td></tr>}</tbody></table></div>
      </section>
    </main>
    {notice&&<div className="fixed bottom-5 left-1/2 -translate-x-1/2 rounded-lg bg-emerald-600 px-4 py-2 text-sm text-white shadow-lg">{notice}</div>}
    {routeLog&&<ManualModal log={routeLog} departments={departments} tr={tr} onClose={()=>setRouteLog(null)} onDone={()=>{setRouteLog(null);load()}}/>}
    {modal&&<SettingsModal settings={settings} setField={setField} departments={departments} tr={tr} onClose={()=>setModal(false)} onSave={saveSettings}/>} 
  </div>
}
function Stat({icon,label,value,color}) { const c={indigo:'bg-indigo-50 text-indigo-600 dark:bg-indigo-950',emerald:'bg-emerald-50 text-emerald-600 dark:bg-emerald-950',rose:'bg-rose-50 text-rose-600 dark:bg-rose-950'}[color]; return <div className="stat-card flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className={`rounded-xl p-3 ${c}`}>{React.cloneElement(icon,{size:21})}</div><div><div className="text-2xl font-bold">{value}</div><div className="text-sm text-slate-500">{label}</div></div></div> }
function Modal({title,onClose,children,footer}) { return <div className="modal-backdrop fixed inset-0 z-20 flex items-center justify-center bg-slate-950/50 p-4"><div className="modal-card max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white shadow-xl dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-800"><h3 className="font-semibold">{title}</h3><button onClick={onClose} className="rounded-lg p-1 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"><X size={18}/></button></div>{children}{footer}</div></div> }
function ManualModal({log,departments,tr,onClose,onDone}) { const [department,setDepartment]=useState(departments[0]?.name||''); const [busy,setBusy]=useState(false); const send=async()=>{setBusy(true);await fetch(`${API}/logs/${log.id}/forward`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({department})});setBusy(false);onDone()}; return <Modal title={tr.manual} onClose={onClose}><div className="space-y-4 p-5"><p className="text-sm text-slate-500">{log.subject}</p><select value={department} onChange={e=>setDepartment(e.target.value)} className="w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 text-sm dark:border-slate-700"><option value="">{tr.choose}</option>{departments.map(d=><option key={d.name}>{d.name}</option>)}</select><div className="flex justify-end gap-2"><button onClick={onClose} className="rounded-lg px-4 py-2 text-sm">{tr.cancel}</button><button disabled={busy||!department} onClick={send} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white disabled:opacity-50">{tr.send}</button></div></div></Modal> }
function SettingsModal({settings,setField,departments,tr,onClose,onSave}) { return <Modal title={tr.settings} onClose={onClose}><form onSubmit={onSave} className="space-y-5 p-5"><h4 className="font-medium">{tr.connection}</h4><div className="grid gap-3 sm:grid-cols-2">{[['imap_host','IMAP host'],['imap_port','IMAP port'],['imap_user','IMAP user'],['imap_password','IMAP password'],['smtp_host','SMTP host'],['smtp_port','SMTP port'],['smtp_user','SMTP user'],['smtp_password','SMTP password'],['from_email','From email'],['ollama_url','Ollama URL'],['ollama_model','Ollama model'],['check_interval',tr.interval]].map(([key,label])=><label key={key} className="text-xs text-slate-500">{label}<input type={key.includes('password')?'password':'text'} value={settings[key]??''} onChange={e=>setField(key,e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 text-sm text-slate-900 outline-none focus:border-indigo-500 dark:border-slate-700 dark:text-white"/></label>)}</div><h4 className="font-medium">{tr.target}</h4><div className="grid gap-3 sm:grid-cols-2">{departments.map(d=><label key={d.name} className="text-xs text-slate-500">{d.name}<input value={settings.targets?.[d.name]||d.email} onChange={e=>setField('targets',{...settings.targets,[d.name]:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 text-sm dark:border-slate-700"/></label>)}</div><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg px-4 py-2 text-sm">{tr.cancel}</button><button className="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white">{tr.save}</button></div></form></Modal> }

createRoot(document.getElementById('root')).render(<App />)
